-- Generated from generator/demo_specs/aws-philippines-retail-delivery.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-retail-delivery
-- This is the schema that is actually deployed for PH_RETAIL_DELIVERY.

-- Alerts fire on the bottom tail of On-Time Rate
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ON_TIME_RATE) AS T
  FROM RAW.LOCATION_DATA
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ON_TIME_RATE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_RATE), 2) AS AVG_ON_TIME_RATE,
  ROUND(AVG(f.KPI_AVG_DELIVERY_TIME), 2) AS AVG_DELIVERY_TIME,
  ROUND(AVG(f.KPI_FUEL_COST_DELIVERY), 2) AS AVG_FUEL_COST_DELIVERY,
  ROUND(AVG(f.KPI_FAILED_DELIVERY), 2) AS AVG_FAILED_DELIVERY,
  ROUND(AVG(f.KPI_RIDER_UTILIZATION), 2) AS AVG_RIDER_UTILIZATION
FROM RAW.LOCATION_DATA f
JOIN RAW.DELIVERY_HUBS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_RATE), 2) AS AVG_ON_TIME_RATE,
  ROUND(AVG(f.KPI_AVG_DELIVERY_TIME), 2) AS AVG_DELIVERY_TIME,
  ROUND(AVG(f.KPI_FUEL_COST_DELIVERY), 2) AS AVG_FUEL_COST_DELIVERY,
  ROUND(AVG(f.KPI_FAILED_DELIVERY), 2) AS AVG_FAILED_DELIVERY,
  ROUND(AVG(f.KPI_RIDER_UTILIZATION), 2) AS AVG_RIDER_UTILIZATION
FROM RAW.LOCATION_DATA f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ON_TIME_RATE) AS KPI_ON_TIME_RATE, AVG(KPI_AVG_DELIVERY_TIME) AS KPI_AVG_DELIVERY_TIME, AVG(KPI_FUEL_COST_DELIVERY) AS KPI_FUEL_COST_DELIVERY, AVG(KPI_FAILED_DELIVERY) AS KPI_FAILED_DELIVERY, AVG(KPI_RIDER_UTILIZATION) AS KPI_RIDER_UTILIZATION FROM RAW.LOCATION_DATA),
     en AS (SELECT SUM(KPI_DELIVERIES_MTD) AS KPI_DELIVERIES_MTD, SUM(KPI_ACTIVE_RIDERS) AS KPI_ACTIVE_RIDERS FROM RAW.DELIVERY_HUBS)
  SELECT 1 AS SORT_ORDER, 'Deliveries (MTD)' AS TITLE, KPI_DELIVERIES_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_DELIVERIES_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'On-Time Rate' AS TITLE, KPI_ON_TIME_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Delivery Time' AS TITLE, KPI_AVG_DELIVERY_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_DELIVERY_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Riders' AS TITLE, KPI_ACTIVE_RIDERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_RIDERS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Fuel Cost/Delivery' AS TITLE, KPI_FUEL_COST_DELIVERY AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND((KPI_FUEL_COST_DELIVERY)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Failed Delivery' AS TITLE, KPI_FAILED_DELIVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FAILED_DELIVERY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Rider Utilization' AS TITLE, KPI_RIDER_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RIDER_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
