-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Last-Mile Delivery Optimization & Geospatial Intelligence
-- ============================================================================
USE DATABASE DELIVERY_LOGISTICS;
USE SCHEMA ML;

-- ML.FORECAST: DELIVERY_VOLUME_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DELIVERY_VOLUME_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_FORECAST_INPUT'),
  SERIES_COLNAME => 'ZONE_H3',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_PARCELS'
  
);

CREATE OR REPLACE TABLE ML.DELIVERY_VOLUME_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.DELIVERY_VOLUME_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.CLASSIFICATION: DELIVERY_FAILURE_PREDICTOR
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.DELIVERY_FAILURE_PREDICTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FAILED_DELIVERY_ANALYSIS'),
  TARGET_COLNAME => 'WILL_FAIL'
);

