-- ============================================================================
-- 99_RESET.SQL — Reset Last-Mile Delivery Optimization & Geospatial Intelligence to clean demo state
-- ============================================================================
USE DATABASE DELIVERY_LOGISTICS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_GPS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_ZONES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ZONE_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.RIDER_UTILIZATION REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_FORECAST_INPUT REFRESH;
ALTER DYNAMIC TABLE CURATED.FAILED_DELIVERY_ANALYSIS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM DELIVERY_LOGISTICS.RAW.PARCELS → 3200000
-- SELECT COUNT(*) FROM DELIVERY_LOGISTICS.RAW.LOCATION_DATA → 8500000
-- SELECT COUNT(DISTINCT ZONE_H3) FROM DELIVERY_LOGISTICS.CURATED.ZONE_PERFORMANCE WHERE SUCCESS_RATE < 0.85 → 14

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_ZONES RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_GPS RESUME;
